### ISSUE TITLE
Add example for boolean operators to documentation

### ISSUE THREAD

**Issue by hauschke** [J535D165/pyalex#11]
Thanks for providing pyalex! It would be helpful to have an example for the use of different boolean filters in the Readme. 

Example URL: https://api.openalex.org/works?filter=institutions.country_code:tw,institutions.country_code:hk

**Comment by J535D165** [comment]
Thanks for the question. It seems like I forgot to implement this feature. I will work on a series of pull requests to implement this feature. Expect an update soon.

**Comment by J535D165** [comment]
Support for all logical expressions is there :) Please have a look at the README for details. You can upgrade to the latest version to get this work.
