### ISSUE TITLE
filter by attributes containing `.`

### ISSUE THREAD

**Issue by lfoppiano** [J535D165/pyalex#22]
Hi, 
   I'm trying to collect works based on filtering through concepts, for example: 

https://api.openalex.org/works?filter=concept_id:https://openalex.org/C555008776

however, I cannot find the way to pass the "concept.id" as a parameter in 

`Works().filter(...)`

maybe I missed something? 

Thank you in advance

**Comment by lfoppiano** [comment]
5 seconds after opening this I found the solution, I guess it's something like: 

`Works().filter(concept={"id": "https://openalex.org/C555008776"})` 

😅

**Comment by J535D165** [comment]
No worries, this is the most confusing part of the API :) I will think about improved documentation on this.
